language: android

sudo: false

jdk:
  - oraclejdk8

env:
  - JPM_HOME=${HOME}/jpm
  - JPM_BIN=${JPM_HOME}/bin

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - android-23
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-tv-21

before_install:
  - pip install --user codecov
  - curl -sL http://bit.ly/jpm4j > jpm4j.jar
  - java -jar jpm4j.jar --home ${JPM_HOME} --bindir ${JPM_BIN} init
  - ${JPM_BIN}/jpm install com.codacy:codacy-coverage-reporter:assembly

before_script:
  - echo no | android create avd --force -n test -t android-21 --abi android-tv/armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew assemble check connectedCheck

after_success:
  - codecov
  - ${JPM_BIN}/codacy-coverage-reporter --projectToken ${CODACY_PROJECT_TOKEN} --language Java --coverageReport app/build/reports/coverage/debug/report.xml

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
